In [77]:
import pandas as pd
import numpy as np

In [78]:
df = pd.read_csv("Countries.csv")

In [79]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [80]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [81]:
df.tail()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.2605,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.0000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [82]:
df.shape

(194, 64)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [84]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [85]:
df[df['population'].max() == df['population']]['country']

75    India
Name: country, dtype: object

In [86]:
df[df['population'].min() == df['population']]['capital_city']

179    Funafuti
Name: capital_city, dtype: object

In [87]:
df[df['population'].min() == df['population']]['country']

179    Tuvalu
Name: country, dtype: object

In [88]:
df.sort_values(by='democracy_score',ascending=False).head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [89]:
count = 0
for i,v in df.groupby('region'):
  count += 1

print(f"THere are {count} no. of regions")

THere are 22 no. of regions

In [90]:
count = 0
for i,v in df.groupby('region'):
  print(i)
  print(v)

Australia and New Zealand
         country               country_long            currency capital_city  \
8      Australia  Commonwealth of Australia   Australian dollar     Canberra
122  New Zealand                New Zealand  New Zealand dollar   Wellington

                        region continent        demonym  latitude  longitude  \
8    Australia and New Zealand   Oceania     Australian     -27.0      133.0
122  Australia and New Zealand   Oceania  New Zealander     -41.0      174.0

     agricultural_land  ...  population  women_parliament_seats_pct  \
8            3557750.0  ...    25978935                     38.4106
122           101540.0  ...     5124100                     50.4202

     rural_population  urban_population  press  democracy_score  \
8             3510274          22468661   4.73             9.09
122            672077           4452023   7.27             9.26

     democracy_type  median_age  political_leader           title
8    Full democracy        33.3  Anthony Albanese  Prime Minister
122  Full democracy        32.8    Jacinda Ardern  Prime Minister

[2 rows x 64 columns]
Caribbean
                            country                     country_long  \
5               Antigua and Barbuda              Antigua and Barbuda
13                         Barbados                         Barbados
41                             Cuba                 Republic of Cuba
48                         Dominica         Commonwealth of Dominica
49               Dominican Republic               Dominican Republic
66                          Grenada                          Grenada
71                            Haiti                Republic of Haiti
82                          Jamaica                          Jamaica
159             St. Kitts and Nevis              St. Kitts and Nevis
160                       St. Lucia                        St. Lucia
161  St. Vincent and the Grenadines   St. Vincent and the Grenadines
170                     The Bahamas      Commonwealth of The Bahamas
175             Trinidad and Tobago  Republic of Trinidad and Tobago

                       currency    capital_city     region continent  \
5         East Caribbean dollar    Saint John's  Caribbean  Americas
13              Barbados dollar      Bridgetown  Caribbean  Americas
41                   Cuban peso          Havana  Caribbean  Americas
48        East Caribbean dollar          Roseau  Caribbean  Americas
49               Dominican peso   Santo Domingo  Caribbean  Americas
66        East Caribbean dollar    St. George's  Caribbean  Americas
71               Haitian gourde  Port-au-Prince  Caribbean  Americas
82              Jamaican dollar        Kingston  Caribbean  Americas
159       East Caribbean dollar      Basseterre  Caribbean  Americas
160       East Caribbean dollar        Castries  Caribbean  Americas
161       East Caribbean dollar       Kingstown  Caribbean  Americas
170             Bahamian dollar          Nassau  Caribbean  Americas
175  Trinidad and Tobago dollar   Port of Spain  Caribbean  Americas

                  demonym   latitude  longitude  agricultural_land  ...  \
5                Antiguan  17.050000 -61.800000               90.0  ...
13              Barbadian  13.166667 -59.533333              100.0  ...
41                  Cuban  21.500000 -80.000000            64010.0  ...
48              Dominican  15.416667 -61.333333              250.0  ...
49              Dominican  19.000000 -70.666667            24290.0  ...
66              Grenadian  12.116667 -61.666667               80.0  ...
71                Haitian  19.000000 -72.416667            18400.0  ...
82               Jamaican  18.250000 -77.500000             4440.0  ...
159  Kittian and Nevisian  17.333333 -62.750000               60.0  ...
160          Saint Lucian  13.883333 -60.966667               99.4  ...
161      Saint Vincentian  13.250000 -61.200000               70.0  ...
170              Bahamian  24.250000 -76.000000              140.0  ...
175           Trinidadian  11.000000 -61.000000              540.0  ...

     population  women_parliament_seats_pct  rural_population  \
5         93763                    11.11110             70935
13       281635                    26.66670            193416
41     11212191                    53.41300           2533843
48        72737                    34.37500             20585
49     11228821                    27.89470           1813679
66       125438                    31.25000             79192
71     11584996                     2.54237           4770701
82      2827377                    28.57140           1215546
159       47657                    31.25000             32888
160      179857                    11.11110            145594
161      103948                    18.18180             47946
170      409984                    17.94870             67680
175     1531044                    26.19050            714385

     urban_population  press  democracy_score    democracy_type  median_age  \
5               22828   0.00             0.00           Unknown        31.1
13              88219   0.00             0.00           Unknown        35.2
41            8678348   1.23             3.00     Authoritarian        37.2
48              52152   0.00             0.00           Unknown        28.1
49            9415142   2.80             6.54  Flawed democracy        23.4
66              46246   0.00             0.00           Unknown        27.1
71            6814295   2.70             4.91     Hybrid regime        19.3
82            1611831   7.03             7.02  Flawed democracy        27.3
159             14769   0.00             0.00           Unknown        30.4
160             34263   0.00             0.00           Unknown        29.5
161             56002   0.00             0.00           Unknown        29.1
170            342304   0.00             0.00           Unknown        28.9
175            816659   3.16             7.16  Flawed democracy        31.9

      political_leader                                   title
5        Gaston Browne                          Prime Minister
13         Mia Mottley                          Prime Minister
41         Raúl Castro  First Secretary of the Communist Party
48   Roosevelt Skerrit                          Prime Minister
49       Danilo Medina                               President
66      Keith Mitchell                          Prime Minister
71       Jovenel Moïse                               President
82      Andrew Holness                          Prime Minister
159                NaN                                     NaN
160                NaN                                     NaN
161                NaN                                     NaN
170      Hubert Minnis                          Prime Minister
175       Keith Rowley                          Prime Minister

[13 rows x 64 columns]
Central America
         country             country_long                 currency  \
16        Belize                   Belize            Belize dollar
38    Costa Rica   Republic of Costa Rica        Costa Rican colon
52   El Salvador  Republic of El Salvador              U.S. dollar
67     Guatemala    Republic of Guatemala       Guatemalan quetzal
72      Honduras     Republic of Honduras         Honduran lempira
109       Mexico    United Mexican States             Mexican peso
123    Nicaragua    Republic of Nicaragua  Nicaraguan gold cordoba
131       Panama       Republic of Panama        Panamanian balboa

       capital_city           region continent      demonym   latitude  \
16         Belmopan  Central America  Americas     Belizean  17.250000
38         San José  Central America  Americas  Costa Rican  10.000000
52     San Salvador  Central America  Americas   Salvadoran  13.833333
67   Guatemala City  Central America  Americas   Guatemalan  15.500000
72      Tegucigalpa  Central America  Americas     Honduran  15.000000
109     Mexico City  Central America  Americas      Mexican  23.000000
123         Managua  Central America  Americas   Nicaraguan  13.000000
131     Panama City  Central America  Americas   Panamanian   9.000000

      longitude  agricultural_land  ...  population  \
16   -88.750000             1720.0  ...      405272
38   -84.000000            17615.0  ...     5180829
52   -88.916667            11957.0  ...     6336392
67   -90.250000            38560.0  ...    17357886
72   -86.500000            35110.0  ...    10432860
109 -102.000000           971380.0  ...   127504125
123  -85.000000            50650.0  ...     6948392
131  -80.000000            21741.0  ...     4408581

     women_parliament_seats_pct  rural_population  urban_population  press  \
16                      12.5000            217242            188030   2.84
38                      47.3684            930373           4250456   6.39
52                      27.3810           1598862           4737530   2.62
67                      19.3750           8216182           9141704   2.18
72                      27.3438           4214875           6217985   1.61
109                     50.0000          23843271         103660854   1.67
123                     51.6483           2810208           4138184   2.20
131                     22.5352           1360444           3048137   2.63

     democracy_score    democracy_type  median_age  \
16              0.00           Unknown        21.6
38              8.07    Full democracy        29.3
52              5.96     Hybrid regime        22.8
67              5.60     Hybrid regime        18.5
72              5.63     Hybrid regime        19.8
109             6.19  Flawed democracy        25.4
123             3.63     Authoritarian        20.9
131             7.05  Flawed democracy        25.1

                political_leader           title
16                   Dean Barrow  Prime Minister
38       Carlos Alvarado Quesada       President
52                  Nayib Bukele       President
67          Alejandro Giammattei       President
72        Juan Orlando Hernández       President
109  Andrés Manuel López Obrador       President
123                Daniel Ortega       President
131           Laurentino Cortizo       President

[8 rows x 64 columns]
Central Asia
             country            country_long           currency capital_city  \
85        Kazakhstan  Republic of Kazakhstan       Kazakh tenge       Astana
90   Kyrgyz Republic         Kyrgyz Republic         Kyrgyz som      Bishkek
167       Tajikistan  Republic of Tajikistan       Tajik somoni     Dushanbe
178     Turkmenistan            Turkmenistan  New Turkmen manat     Ashgabat
186       Uzbekistan  Republic of Uzbekistan          Uzbek som     Tashkent

           region continent      demonym  latitude  longitude  \
85   Central Asia      Asia  Kazakhstani      48.0       68.0
90   Central Asia      Asia      Kirghiz      41.0       75.0
167  Central Asia      Asia      Tadzhik      39.0       71.0
178  Central Asia      Asia      Turkmen      40.0       60.0
186  Central Asia      Asia  Uzbekistani      41.0       64.0

     agricultural_land  ...  population  women_parliament_seats_pct  \
85           2140030.0  ...    19621972                     27.3585
90            103678.0  ...     6803300                     20.4545
167            49160.0  ...     9952787                     26.9841
178           338380.0  ...     6430770                     25.8621
186           256825.0  ...    35648100                     33.3333

     rural_population  urban_population  press  democracy_score  \
85            8243190          11378782   1.48             2.94
90            4254716           2548584   2.61             5.11
167           7169192           2783595   1.45             1.93
178           2990694           3440076   0.92             1.72
186          17657930          17990170   1.46             2.01

     democracy_type  median_age           political_leader           title
85    Authoritarian        25.5       Qasym-Zhomart Toqaev       President
90    Hybrid regime        19.8  Mukhammedkalyi Abylgaziev  Prime Minister
167   Authoritarian        17.7             Emomali Rahmon       President
178   Authoritarian        22.0  Gurbanguly Berdimuhamedow       President
186   Authoritarian        22.7         Shavkat Mirziyoyev       President

[5 rows x 64 columns]
Eastern Africa
        country                             country_long  \
26      Burundi                      Republic of Burundi
36      Comoros                     Union of the Comoros
47     Djibouti                     Republic of Djibouti
54      Eritrea                         State of Eritrea
57     Ethiopia  Federal Democratic Republic of Ethiopia
86        Kenya                        Republic of Kenya
100  Madagascar                   Republic of Madagascar
101      Malawi                       Republic of Malawi
108   Mauritius                    Republic of Mauritius
116  Mozambique                   Republic of Mozambique
141      Rwanda                       Republic of Rwanda
148  Seychelles                   Republic of Seychelles
154     Somalia               Somali Democratic Republic
168    Tanzania              United Republic of Tanzania
180      Uganda                       Republic of Uganda
192      Zambia                       Republic of Zambia
193    Zimbabwe                     Republic of Zimbabwe

                   currency  capital_city          region continent  \
26            Burundi franc     Bujumbura  Eastern Africa    Africa
36           Comorian franc        Moroni  Eastern Africa    Africa
47           Djibouti franc      Djibouti  Eastern Africa    Africa
54           Eritrean nakfa        Asmara  Eastern Africa    Africa
57           Ethiopian birr   Addis Ababa  Eastern Africa    Africa
86          Kenyan shilling       Nairobi  Eastern Africa    Africa
100         Malagasy ariary  Antananarivo  Eastern Africa    Africa
101           Malawi kwacha      Lilongwe  Eastern Africa    Africa
108         Mauritian rupee    Port Louis  Eastern Africa    Africa
116  New Mozambican metical        Maputo  Eastern Africa    Africa
141           Rwandan franc        Kigali  Eastern Africa    Africa
148        Seychelles rupee      Victoria  Eastern Africa    Africa
154         Somali shilling     Mogadishu  Eastern Africa    Africa
168      Tanzanian shilling        Dodoma  Eastern Africa    Africa
180        Ugandan shilling       Kampala  Eastern Africa    Africa
192      New Zambian kwacha        Lusaka  Eastern Africa    Africa
193             U.S. dollar        Harare  Eastern Africa    Africa

         demonym   latitude  longitude  agricultural_land  ...  population  \
26     Burundian  -3.500000  30.000000            20330.0  ...    12889576
36       Comoran -12.166667  44.250000             1310.0  ...      836774
47      Djibouti  11.500000  43.000000            17020.0  ...     1120849
54      Eritrean  15.000000  39.000000            75920.0  ...     3684032
57     Ethiopian   8.000000  38.000000           384761.0  ...   123379924
86        Kenyan   1.000000  38.000000           276300.0  ...    54027487
100     Malagasy -20.000000  47.000000           408950.0  ...    29611714
101     Malawian -13.500000  34.000000            56500.0  ...    20405317
108    Mauritian -20.283333  57.550000              860.0  ...     1262523
116   Mozambican -18.250000  35.000000           414138.0  ...    32969518
141      Rwandan  -2.000000  30.000000            18117.0  ...    13776698
148  Seychellois  -4.583333  55.666667               15.5  ...      100060
154       Somali  10.000000  49.000000           441250.0  ...    17597511
168    Tanzanian  -6.000000  35.000000           395212.0  ...    65497748
180      Ugandan   1.000000  32.000000           144150.0  ...    47249585
192      Zambian -15.000000  30.000000           238360.0  ...    20017675
193   Zimbabwean -20.000000  30.000000           162000.0  ...    16320537

     women_parliament_seats_pct  rural_population  urban_population  press  \
26                      38.2114          11031286           1858290   1.48
36                      16.6667            586880            249894   2.80
47                      26.1538            242328            878521   1.10
54                      22.0000           2113713           1570319   0.97
57                      41.4894          95420799          27959125   2.23
86                      23.4286          38358435          15669052   2.41
100                     18.5430          17801970          11809744   2.82
101                     22.9167          16736441           3668876   2.66
108                     20.0000            747287            515236   2.75
116                     42.4000          20379448          12590070   2.39
141                     61.2500          11335329           2441369   1.49
148                     22.8571             41629             58431   2.66
154                     19.7080           9269665           8327846   1.37
168                     36.8557          41471864          24025884   2.16
180                     33.8130          34889566          12360019   1.98
192                     15.0602          10857387           9160288   2.15
193                     30.5660          11033499           5287038   1.85

     democracy_score  democracy_type  median_age     political_leader  \
26              2.33   Authoritarian        11.9    Pierre Nkurunziza
36              3.71   Authoritarian        16.3      Azali Assoumani
47              2.87   Authoritarian        20.0  Ismaïl Omar Guelleh
54              2.37   Authoritarian        14.5       Isaias Afwerki
57              3.35   Authoritarian        14.7           Abiy Ahmed
86              5.11   Hybrid regime        15.4       Uhuru Kenyatta
100             5.22   Hybrid regime        15.1      Andry Rajoelina
101             5.49   Hybrid regime        13.1      Peter Mutharika
108             8.22  Full democracy        33.1     Pravind Jugnauth
116             3.85   Authoritarian        13.0         Filipe Nyusi
141             3.35   Authoritarian        15.2          Paul Kagame
148             0.00         Unknown        28.8          Danny Faure
154             0.00         Unknown        11.3    Hassan Ali Khayre
168             5.41   Hybrid regime        13.0        John Magufuli
180             5.20   Hybrid regime        12.2      Yoweri Museveni
192             5.61   Hybrid regime        13.2          Edgar Lungu
193             3.16   Authoritarian        14.2   Emmerson Mnangagwa

              title
26        President
36        President
47        President
54        President
57   Prime Minister
86        President
100       President
101       President
108  Prime Minister
116       President
141       President
148       President
154  Prime Minister
168       President
180       President
192       President
193       President

[17 rows x 64 columns]
Eastern Asia
                      country                           country_long  \
34                      China             People's Republic of China
44   Dem. People's Rep. Korea  Democratic People's Republic of Korea
83                      Japan                                  Japan
88                      Korea                      Republic of Korea
113                  Mongolia                               Mongolia

                                       currency capital_city        region  \
34                                 Chinese yuan      Beijing  Eastern Asia
44   Democratic People's Republic of Korean won    Pyongyang  Eastern Asia
83                                 Japanese yen        Tokyo  Eastern Asia
88                                   Korean won        Seoul  Eastern Asia
113                            Mongolian tugrik   Ulan Bator  Eastern Asia

    continent       demonym  latitude  longitude  agricultural_land  ...  \

In [91]:
df['region'].value_counts()['Eastern Europe']

np.int64(10)

In [92]:
df[df['population'] == df['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: object

In [93]:
df.loc[df['political_leader'].isna()]['country'].count()

np.int64(7)

In [96]:
count = 0
def count_republic(txt):
  global count
  if 'republic' in txt.lower():
    count += 1

df['country_long'].apply(count_republic)
print("republic: ",count)

republic:  125

In [101]:
africa_df = df[df['continent']=='Africa']

In [102]:
africa_df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.0,...,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.0,...,2630296,11.11110,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.0,...,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.0,...,27914536,33.88890,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.0,...,5579144,12.85710,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President
32,Chad,Republic of Chad,Central African CFA franc,N'Djamena,Middle Africa,Africa,Chadian,15.000000,19.000000,502380.0,...,17723315,25.88830,13458554,4264761,2.13,1.61,Authoritarian,11.2,Idriss Déby,President
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.0,...,836774,16.66670,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
37,Congo,Republic of Congo,Central African CFA franc,Brazzaville,Middle Africa,Africa,Congolese,-1.000000,15.000000,106280.0,...,5970424,14.56950,1866593,4103831,2.17,3.31,Authoritarian,14.3,Denis Sassou Nguesso,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
45,Dem. Rep. Congo,Democratic Republic of the Congo,Congolese franc,Kinshasa,Middle Africa,Africa,Congolese,0.000000,25.000000,335720.0,...,99010212,12.80000,52636799,46373413,1.51,1.49,Authoritarian,11.7,Félix Tshisekedi,President
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,...,1120849,26.15380,242328,878521,1.10,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President
51,Egypt,Arab Republic of Egypt,Egyptian pound,Cairo,Northern Africa,Africa,Egyptian,27.000000,30.000000,39710.0,...,110990103,27.58040,63300985,47689118,1.38,3.36,Authoritarian,20.1,Abdel Fattah el-Sisi,President
53,Equatorial Guinea,Republic of Equatorial Guinea,Central African CFA franc,Malabo,Middle Africa,Africa,Equatorial Guinean,2.000000,10.000000,1885.2,...,1674908,31.00000,435309,1239599,1.34,1.92,Authoritarian,16.8,Teodoro Obiang Nguema Mbasogo,President
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.000000,39.000000,75920.0,...,3684032,22.00000,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President
56,Eswatini,Kingdom of Eswatini,Swazi lilangeni,Lobamba,Southern Africa,Africa,Swazi,-26.500000,31.500000,12220.0,...,1201670,13.51350,906348,295322,1.59,3.03,Authoritarian,17.7,Mswati III,King
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.0,...,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
61,Gabon,Gabonese Republic,Central African CFA franc,Libreville,Middle Africa,Africa,Gabonese,-1.000000,11.750000,22126.4,...,2388992,15.38460,221340,2167652,2.20,3.61,Authoritarian,17.7,Ali Bongo Ondimba,President
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,...,33475870,14.54550,13853989,19621881,3.76,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President
68,Guinea,Republic of Guinea,Guinean franc,Conakry,Western Africa,Africa,Guinean,11.000000,-10.000000,145000.0,...,13859341,29.62960,8638804,5220537,2.34,3.14,Authoritarian,13.9,Alpha Condé,President
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.000000,-15.000000,8151.1,...,2105566,13.72550,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President
86,Kenya,Republic of Kenya,Kenyan shilling,Nairobi,Eastern Africa,Africa,Kenyan,1.000000,38.000000,276300.0,...,54027487,23.42860,38358435,15669052,2.41,5.11,Hybrid regime,15.4,Uhuru Kenyatta,President
94,Lesotho,Kingdom of Lesotho,Lesotho loti,Maseru,Southern Africa,Africa,Mosotho,-29.500000,28.500000,26000.0,...,2305825,26.44630,1615392,690433,2.63,6.64,Flawed democracy,18.2,Tom Thabane,Prime Minister
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5302681,10.95890,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
96,Libya,Socialist People's Libyan Arab Jamahiriya,Libyan dinar,Tripoli,Northern Africa,Africa,Libyan,25.000000,17.000000,153500.0,...,6812341,16.47060,1273772,5538569,1.40,2.19,Authoritarian,22.6,Fayez al-Sarraj,Prime Minister
100,Madagascar,Republic of Madagascar,Malagasy ariary,Antananarivo,Eastern Africa,Africa,Malagasy,-20.000000,47.000000,408950.0,...,29611714,18.54300,17801970,11809744,2.82,5.22,Hybrid regime,15.1,Andry Rajoelina,President
101,Malawi,Republic of Malawi,Malawi kwacha,Lilongwe,Eastern Africa,Africa,Malawian,-13.500000,34.000000,56500.0,...,20405317,22.91670,16736441,3668876,2.66,5.49,Hybrid regime,13.1,Peter Mutharika,President
104,Mali,Republic of Mali,West African CFA franc,Bamako,Western Africa,Africa,Malian,17.000000,-4.000000,412010.0,...,22593590,28.57140,12327741,10265849,2.22,5.41,Hybrid regime,11.3,Ibrahim Boubacar Keïta,President
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,...,4736139,20.26140,2040187,2695952,2.47,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.550000,860.0,...,1262523,20.00000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
115,Morocco,Kingdom of Morocco,Moroccan dirham,Rabat,Northern Africa,Africa,Moroccan,32.000000,-5.000000,303820.0,...,37457971,24.05060,13261620,24196351,1.78,4.99,Hybrid regime,25.0,Mohammed VI,King
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.250000,35.000000,414138.0,...,32969518,42.40000,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President
118,Namibia,Republic of Namibia,Namibian dollar,Windhoek,Southern Africa,Africa,Namibian,-22.000000,17.000000,388100.0,...,2567012,44.23080,1181955,1385057,4.13,6.25,Flawed democracy,17.4,Hage Geingob,President
124,Niger,Republic of Niger,West African CFA franc,Niamey,Western Africa,Africa,Nigerien,16.000000,8.000000,465970.0,...,26207977,25.90360,21780401,4427576,2.67,3.76,Authoritarian,10.5,Mahamadou Issoufou,President
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President
141,Rwanda,Republic of Rwanda,Rwandan franc,Kigali,Eastern Africa,Africa,Rwandan,-2.000000,30.000000,18117.0,...,13776698,61.25000,11335329,2441369,1.49,3.35,Authoritarian,15.2,Paul Kagame,President
144,São Tomé and Principe,Democratic Republic of São Tomé and Principe,São Tomé and Principe dobra,São Tomé,Middle Africa,Africa,Sao Tomean,1.000000,7.000000,440.0,...,227380,14.54550,55128,172252,0.00,0.00,Unknown,14.6,Evaristo Carvalho,President
146,Senegal,Republic of Senegal,West African CFA franc,Dakar,Western Africa,Africa,Senegalese,14.000000,-14.000000,88780.0,...,17316449,44.24240,8816497,8499952,3.03,6.15,Flawed democracy,14.0,Macky Sall,President
148,Seychelles,Republic of Seychelles,Seychelles rupee,Victoria,Eastern Africa,Africa,Seychellois,-4.583333,55.666667,15.5,...,100060,22.85710,41629,58431,2.66,0.00,Unknown,28.8,Danny Faure,President
149,Sierra Leone,Republic of Sierra Leone,Sierra Leonean leone,Freetown,Western Africa,Africa,Sierra Leonean,8.500000,-11.500000,39490.0,...,8605718,12.32880,4833746,3771972,2.58,4.66,Hybrid regime,15.1,Julius Maada Bio,President
154,Somalia,Somali Democratic Republic,Somali shilling,Mogadishu,Eastern Africa,Africa,Somali,10.000000,49.000000,441250.0,...,17597511,19.70800,9269665,8327846,1.37,0.00,Unknown,11.3,Hassan Ali Khayre,Prime Minister
155,South Africa,Republic of South Africa,South African rand,Pretoria,Southern Africa,Africa,South African,-29.000000,24.000000,963410.0,...,59893885,46.50000,18965399,40928486,3.52,7.24,Flawed democracy,23.3,Cyril Ramaphosa,President
156,South Sudan,Republic of South Sudan,South Sudanese Pound,Juba,Middle Africa,Africa,South Sudanese,7.000000,30.000000,282510.0,...,10913164,32.36360,8638206,2274958,1.71,0.00,Unknown,12.5,Salva Kiir Mayardit,President
162,Sudan,Republic of the Sudan,Sudanese pound,Khartoum,Northern Africa,Africa,Sudanese,15.000000,30.000000,694058.0,...,46874204,30.51640,30020115,16854089,1.08,2.15,Authoritarian,14.5,Abdel Fattah al-Burhan,Leader of the Sovereignty Council
168,Tanzania,United Republic of Tanzania,Tanzanian shilling,Dodoma,Eastern Africa,Africa,Tanzanian,-6.000000,35.000000,395212.0,...,65497748,36.85570,41471864,24025884,2.16,5.41,Hybrid regime,13.0,John Magufuli,President
171,The Gambia,Republic of The Gambia,Gambian dalasi,Banjul,Western Africa,Africa,Gambian,13.466667,-16.566667,6050.0,...,2705992,8.62069,978162,1727830,2.49,4.31,Hybrid regime,13.1,Adama Barrow,President
173,Togo,Republic of Togo,West African CFA franc,Lomé,Western Africa,Africa,Togolese,8.000000,1.166667,38200.0,...,8848699,18.68130,4962262,3886437,2.63,3.10,Authoritarian,14.8,Faure Gnassingbé,President
176,Tunisia,Republic of Tunisia,Tunisian dinar,Tunis,Northern Africa,Africa,Tunisian,34.000000,9.000000,97310.0,...,12356117,26.26730,3680393,8675724,2.64,6.41,Flawed democracy,28.0,Kaïs Saïed,President
180,Uganda,Republic of Uganda,Ugandan shilling,Kampala,Eastern Africa,Africa,Ugandan,1.000000,32.000000,144150.0,...,47249585,33.81300,34889566,12360019,1.98,5.20,Hybrid regime,12.2,Yoweri Museveni,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [103]:
print(len(africa_df))

54

In [107]:
africa_df[africa_df['population'].max()==africa_df['population']]['country']

125    Nigeria
Name: country, dtype: object